"""overhaul_rules_and_add_moderation_tables

Revision ID: d8163352b057
Revises: 006_enhanced_scanning_system
Create Date: 2025-08-03 01:19:02.679712

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd8163352b057'
down_revision: Union[str, None] = '006_enhanced_scanning_system'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('account_behavior_metrics',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('mastodon_account_id', sa.Text(), nullable=False),
    sa.Column('posts_last_1h', sa.Integer(), nullable=True),
    sa.Column('posts_last_24h', sa.Integer(), nullable=True),
    sa.Column('last_sampled_status_id', sa.Text(), nullable=True),
    sa.Column('last_calculated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('mastodon_account_id')
    )
    op.create_table('interaction_history',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('source_account_id', sa.Text(), nullable=False),
    sa.Column('target_account_id', sa.Text(), nullable=False),
    sa.Column('status_id', sa.Text(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('scheduled_actions',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('mastodon_account_id', sa.Text(), nullable=False),
    sa.Column('action_to_reverse', sa.Enum('report', 'silence', 'suspend', 'disable', 'sensitive', 'domain_block', name='action_type_enum'), nullable=False),
    sa.Column('expires_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scheduled_actions_expires_at'), 'scheduled_actions', ['expires_at'], unique=False)
    op.create_index(op.f('ix_scheduled_actions_mastodon_account_id'), 'scheduled_actions', ['mastodon_account_id'], unique=False)
    op.create_table('audit_log',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('action_type', sa.Text(), nullable=False),
    sa.Column('triggered_by_rule_id', sa.BigInteger(), nullable=True),
    sa.Column('target_account_id', sa.Text(), nullable=False),
    sa.Column('timestamp', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('evidence', sa.JSON(), nullable=True),
    sa.Column('api_response', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['triggered_by_rule_id'], ['rules.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_index('ix_accounts_acct', table_name='accounts')
    op.drop_index('ix_accounts_content_hash', table_name='accounts')
    op.drop_index('ix_accounts_domain', table_name='accounts')
    op.drop_index('ix_accounts_last_checked_at', table_name='accounts')
    op.drop_index('ix_accounts_last_full_scan_at', table_name='accounts')
    op.drop_index('idx_analyses_account', table_name='analyses')
    op.drop_index('idx_analyses_created', table_name='analyses')
    op.drop_index('ix_analyses_created_at', table_name='analyses')
    op.drop_index('ix_analyses_mastodon_account_id_created_at', table_name='analyses')
    op.drop_index('ix_analyses_rule_key', table_name='analyses')
    op.drop_constraint('fk_analyses_mastodon_account_id', 'analyses', type_='foreignkey')
    op.drop_index('ix_content_scans_last_scanned_at', table_name='content_scans')
    op.drop_index('ix_content_scans_mastodon_account_id', table_name='content_scans')
    op.drop_index('ix_content_scans_needs_rescan', table_name='content_scans')
    op.drop_index('ix_content_scans_scan_type', table_name='content_scans')
    op.drop_index('ix_domain_alerts_domain', table_name='domain_alerts')
    op.drop_index('ix_domain_alerts_is_defederated', table_name='domain_alerts')
    op.drop_index('ix_domain_alerts_violation_count', table_name='domain_alerts')
    op.drop_index('ix_reports_created_at', table_name='reports')
    op.drop_index('ix_reports_mastodon_account_id_created_at', table_name='reports')
    op.drop_constraint('fk_reports_mastodon_account_id', 'reports', type_='foreignkey')
    op.add_column('rules', sa.Column('detector_type', sa.Text(), nullable=False))
    op.add_column('rules', sa.Column('action_type', sa.Enum('report', 'silence', 'suspend', 'disable', 'sensitive', 'domain_block', name='action_type_enum'), nullable=False))
    op.add_column('rules', sa.Column('action_duration_seconds', sa.Integer(), nullable=True))
    op.add_column('rules', sa.Column('action_warning_text', sa.Text(), nullable=True))
    op.add_column('rules', sa.Column('warning_preset_id', sa.Text(), nullable=True))
    op.add_column('rules', sa.Column('trigger_threshold', sa.Numeric(), nullable=False))
    op.drop_index('ix_rules_enabled', table_name='rules')
    op.drop_index('ix_rules_is_default', table_name='rules')
    op.drop_index('ix_rules_last_triggered_at', table_name='rules')
    op.drop_index('ix_rules_rule_type', table_name='rules')
    op.drop_index('ix_rules_trigger_count', table_name='rules')
    op.drop_column('rules', 'rule_type')
    op.drop_index('ix_scan_sessions_session_type', table_name='scan_sessions')
    op.drop_index('ix_scan_sessions_started_at', table_name='scan_sessions')
    op.drop_index('ix_scan_sessions_status', table_name='scan_sessions')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_scan_sessions_status', 'scan_sessions', ['status'], unique=False)
    op.create_index('ix_scan_sessions_started_at', 'scan_sessions', ['started_at'], unique=False)
    op.create_index('ix_scan_sessions_session_type', 'scan_sessions', ['session_type'], unique=False)
    op.add_column('rules', sa.Column('rule_type', sa.TEXT(), autoincrement=False, nullable=False))
    op.create_index('ix_rules_trigger_count', 'rules', ['trigger_count'], unique=False)
    op.create_index('ix_rules_rule_type', 'rules', ['rule_type'], unique=False)
    op.create_index('ix_rules_last_triggered_at', 'rules', ['last_triggered_at'], unique=False)
    op.create_index('ix_rules_is_default', 'rules', ['is_default'], unique=False)
    op.create_index('ix_rules_enabled', 'rules', ['enabled'], unique=False)
    op.drop_column('rules', 'trigger_threshold')
    op.drop_column('rules', 'warning_preset_id')
    op.drop_column('rules', 'action_warning_text')
    op.drop_column('rules', 'action_duration_seconds')
    op.drop_column('rules', 'action_type')
    op.drop_column('rules', 'detector_type')
    op.create_foreign_key('fk_reports_mastodon_account_id', 'reports', 'accounts', ['mastodon_account_id'], ['mastodon_account_id'], ondelete='CASCADE')
    op.create_index('ix_reports_mastodon_account_id_created_at', 'reports', ['mastodon_account_id', 'created_at'], unique=False)
    op.create_index('ix_reports_created_at', 'reports', ['created_at'], unique=False)
    op.create_index('ix_domain_alerts_violation_count', 'domain_alerts', ['violation_count'], unique=False)
    op.create_index('ix_domain_alerts_is_defederated', 'domain_alerts', ['is_defederated'], unique=False)
    op.create_index('ix_domain_alerts_domain', 'domain_alerts', ['domain'], unique=False)
    op.create_index('ix_content_scans_scan_type', 'content_scans', ['scan_type'], unique=False)
    op.create_index('ix_content_scans_needs_rescan', 'content_scans', ['needs_rescan'], unique=False)
    op.create_index('ix_content_scans_mastodon_account_id', 'content_scans', ['mastodon_account_id'], unique=False)
    op.create_index('ix_content_scans_last_scanned_at', 'content_scans', ['last_scanned_at'], unique=False)
    op.create_foreign_key('fk_analyses_mastodon_account_id', 'analyses', 'accounts', ['mastodon_account_id'], ['mastodon_account_id'], ondelete='CASCADE')
    op.create_index('ix_analyses_rule_key', 'analyses', ['rule_key'], unique=False)
    op.create_index('ix_analyses_mastodon_account_id_created_at', 'analyses', ['mastodon_account_id', 'created_at'], unique=False)
    op.create_index('ix_analyses_created_at', 'analyses', ['created_at'], unique=False)
    op.create_index('idx_analyses_created', 'analyses', ['created_at'], unique=False)
    op.create_index('idx_analyses_account', 'analyses', ['mastodon_account_id'], unique=False)
    op.create_index('ix_accounts_last_full_scan_at', 'accounts', ['last_full_scan_at'], unique=False)
    op.create_index('ix_accounts_last_checked_at', 'accounts', ['last_checked_at'], unique=False)
    op.create_index('ix_accounts_domain', 'accounts', ['domain'], unique=False)
    op.create_index('ix_accounts_content_hash', 'accounts', ['content_hash'], unique=False)
    op.create_index('ix_accounts_acct', 'accounts', ['acct'], unique=False)
    op.drop_table('audit_log')
    op.drop_index(op.f('ix_scheduled_actions_mastodon_account_id'), table_name='scheduled_actions')
    op.drop_index(op.f('ix_scheduled_actions_expires_at'), table_name='scheduled_actions')
    op.drop_table('scheduled_actions')
    op.drop_table('interaction_history')
    op.drop_table('account_behavior_metrics')
    # ### end Alembic commands ###
