"""overhaul_rules_and_add_moderation_tables

Revision ID: d8163352b057
Revises: 006_scanning_system
Create Date: 2025-08-03 01:19:02.679712

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d8163352b057"
down_revision: str | None = "006_scanning_system"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "account_behavior_metrics",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("mastodon_account_id", sa.Text(), nullable=False),
        sa.Column("posts_last_1h", sa.Integer(), nullable=True),
        sa.Column("posts_last_24h", sa.Integer(), nullable=True),
        sa.Column("last_sampled_status_id", sa.Text(), nullable=True),
        sa.Column("last_calculated_at", sa.TIMESTAMP(timezone=True), server_default=sa.text("now()"), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("mastodon_account_id"),
    )
    op.create_table(
        "interaction_history",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("source_account_id", sa.Text(), nullable=False),
        sa.Column("target_account_id", sa.Text(), nullable=False),
        sa.Column("status_id", sa.Text(), nullable=True),
        sa.Column("created_at", sa.TIMESTAMP(timezone=True), server_default=sa.text("now()"), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "scheduled_actions",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("mastodon_account_id", sa.Text(), nullable=False),
        sa.Column(
            "action_to_reverse",
            sa.Enum("report", "silence", "suspend", "disable", "sensitive", "domain_block", name="action_type_enum"),
            nullable=False,
        ),
        sa.Column("expires_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_scheduled_actions_expires_at"), "scheduled_actions", ["expires_at"], unique=False)
    op.create_index(
        op.f("ix_scheduled_actions_mastodon_account_id"), "scheduled_actions", ["mastodon_account_id"], unique=False
    )
    op.create_table(
        "audit_log",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("action_type", sa.Text(), nullable=False),
        sa.Column("triggered_by_rule_id", sa.BigInteger(), nullable=True),
        sa.Column("target_account_id", sa.Text(), nullable=False),
        sa.Column("timestamp", sa.TIMESTAMP(timezone=True), server_default=sa.text("now()"), nullable=True),
        sa.Column("evidence", sa.JSON(), nullable=True),
        sa.Column("api_response", sa.JSON(), nullable=True),
        sa.ForeignKeyConstraint(
            ["triggered_by_rule_id"],
            ["rules.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.add_column("rules", sa.Column("detector_type", sa.Text(), nullable=False))
    op.add_column(
        "rules",
        sa.Column(
            "action_type",
            sa.Enum("report", "silence", "suspend", "disable", "sensitive", "domain_block", name="action_type_enum"),
            nullable=False,
        ),
    )
    op.add_column("rules", sa.Column("action_duration_seconds", sa.Integer(), nullable=True))
    op.add_column("rules", sa.Column("action_warning_text", sa.Text(), nullable=True))
    op.add_column("rules", sa.Column("warning_preset_id", sa.Text(), nullable=True))
    op.add_column("rules", sa.Column("trigger_threshold", sa.Numeric(), nullable=False))
    # Remove the old rule_type column as it's replaced by detector_type
    op.drop_column("rules", "rule_type")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("rules", sa.Column("rule_type", sa.TEXT(), autoincrement=False, nullable=False))
    op.drop_column("rules", "trigger_threshold")
    op.drop_column("rules", "warning_preset_id")
    op.drop_column("rules", "action_warning_text")
    op.drop_column("rules", "action_duration_seconds")
    op.drop_column("rules", "action_type")
    op.drop_column("rules", "detector_type")
    op.drop_table("audit_log")
    op.drop_index(op.f("ix_scheduled_actions_mastodon_account_id"), table_name="scheduled_actions")
    op.drop_index(op.f("ix_scheduled_actions_expires_at"), table_name="scheduled_actions")
    op.drop_table("scheduled_actions")
    op.drop_table("interaction_history")
    op.drop_table("account_behavior_metrics")
    # ### end Alembic commands ###
