from enum import Enum


class OAuthScope(str, Enum):
    ADMINREAD = "admin:read"
    ADMINREADACCOUNTS = "admin:read:accounts"
    ADMINREADCANONICAL_EMAIL_BLOCKS = "admin:read:canonical_email_blocks"
    ADMINREADDOMAIN_ALLOWS = "admin:read:domain_allows"
    ADMINREADDOMAIN_BLOCKS = "admin:read:domain_blocks"
    ADMINREADEMAIL_DOMAIN_BLOCKS = "admin:read:email_domain_blocks"
    ADMINREADIP_BLOCKS = "admin:read:ip_blocks"
    ADMINREADREPORTS = "admin:read:reports"
    ADMINWRITE = "admin:write"
    ADMINWRITEACCOUNTS = "admin:write:accounts"
    ADMINWRITECANONICAL_EMAIL_BLOCKS = "admin:write:canonical_email_blocks"
    ADMINWRITEDOMAIN_ALLOWS = "admin:write:domain_allows"
    ADMINWRITEDOMAIN_BLOCKS = "admin:write:domain_blocks"
    ADMINWRITEEMAIL_DOMAIN_BLOCKS = "admin:write:email_domain_blocks"
    ADMINWRITEIP_BLOCKS = "admin:write:ip_blocks"
    ADMINWRITEREPORTS = "admin:write:reports"
    FOLLOW = "follow"
    PROFILE = "profile"
    PUSH = "push"
    READ = "read"
    READACCOUNTS = "read:accounts"
    READBLOCKS = "read:blocks"
    READBOOKMARKS = "read:bookmarks"
    READFAVOURITES = "read:favourites"
    READFILTERS = "read:filters"
    READFOLLOWS = "read:follows"
    READLISTS = "read:lists"
    READMUTES = "read:mutes"
    READNOTIFICATIONS = "read:notifications"
    READSEARCH = "read:search"
    READSTATUSES = "read:statuses"
    WRITE = "write"
    WRITEACCOUNTS = "write:accounts"
    WRITEBLOCKS = "write:blocks"
    WRITEBOOKMARKS = "write:bookmarks"
    WRITECONVERSATIONS = "write:conversations"
    WRITEFAVOURITES = "write:favourites"
    WRITEFILTERS = "write:filters"
    WRITEFOLLOWS = "write:follows"
    WRITELISTS = "write:lists"
    WRITEMEDIA = "write:media"
    WRITEMUTES = "write:mutes"
    WRITENOTIFICATIONS = "write:notifications"
    WRITEREPORTS = "write:reports"
    WRITESTATUSES = "write:statuses"

    def __str__(self) -> str:
        return str(self.value)
